services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=your_token
    volumes:
      - /duckdns
    restart: unless-stopped
volumes:
  duckdns: {}